backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "dat-nen" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Bất động sản" # Used in the UI, ie.: "New Post"
    folder: "site/content/dat-nen" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Thông tin phụ", name: "description", widget: "string"}
      - {label: "Giá", name: "price", widget: "string"}
      - {label: "Ngày đăng", name: "date", widget: "datetime"}
      - {label: "Link Google Map", name: "mapUrl", widget: "text"}
      - {label: "Địa chỉ", name: "address", widget: "text"}
      - {label: "Trạng thái", name: "status", widget: "text"}
      - {label: "Tình trạng pháp lý", name: "tinhTrangPhapLy", widget: "text"}
      - {label: "Diện tích", name: "dienTich", widget: "text"}
      - {label: "Đường trước nhà", name: "duongTruocNha", widget: "text"}
      - {label: "Hướng", name: "huong", widget: "text"}
      - {label: "Số tầng", name: "soTang", widget: "text"}
      - {label: "Phòng ngủ", name: "phongNgu", widget: "text"}
      - {label: "Phòng tắm", name: "phongTam", widget: "text"}
      - {label: "Thuộc dự án", name: "thuocDuAn", widget: "text"}
      - {label: "Tiện ích", name: "tienIch", widget: "list", field: {label: "Text", widget: "text"} }
      - {label: "Môi trường xung quanh", name: "moiTruongXungQuanh", widget: "list", field: {label: "Text", widget: "text"} }
      - {label: "Ảnh chính", name: "image", widget: "image", required: true}
      - {label: "Ảnh phụ", name: "images", widget: "list", required: true, field: {label: "Image", widget: "image"}}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Trang"
    files:
      - file: "site/content/_index.md"
        label: "Trang chủ"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Album ảnh", name: "carouselImages", widget: "list", required: true, field: {label: "Image", widget: "image"}}
          - {label: "Chữ lớn trong hình", name: "carouselTitle", widget: string}
          - {label: "Chữ nhỏ trong hình", name: "carouselSubtitle", widget: string}
          - {label: "Tên phân đoạn", name: "sectionTitle", widget: string}
      - file: "site/data/info.yaml"
        label: "Thông tin chung"
        name: "info"
        fields:
          - {label: "Chữ Logo 1", name: "logo1", widget: string}
          - {label: "Chữ Logo 2", name: "logo2", widget: string}
          - {label: "Chữ Logo 3", name: "logo3", widget: string}
          - {label: "Số điện thoại", name: "phone", widget: string}
          - {label: "Số viber", name: "viber", widget: string}
          - {label: "Số zalo", name: "zalo", widget: string}
          - {label: "Địa chỉ công ty", name: "address", widget: string}
          - {label: "Địa chỉ email", name: "email", widget: string}
          - {label: "Địa chỉ web", name: "website", widget: string}
          - {label: "Link google map", name: "mapUrl", widget: string}
